### ISSUE TITLE
we should probably discuss whether or not we should all meet before brussels

### ISSUE THREAD

**Issue by rewinded** [AutonomousCarProject/CarControl#121]
whats the status of the car, are there any crucial modifications that still need to be done?

@everyone

**Comment by sameer-s** [comment]
No crucial changes that I know of but we should really do some refinements (stop signs being the most important thing). Also getting those uncommitted changes off the car and onto GitHub.

**Comment by sameer-s** [comment]
Just talked to Steve. He said that we should find a time to get testing and make sure that **both** cars are running before we go to Brussels. To those who are interested in helping out with this, let's try to figure out a time that'll work. Preferably send it sooner rather than later (hopefully we can test this weekend or next week) since we're going to need time to fix any major problems that might come up.

**Comment by rewinded** [comment]
almost any time will work for me (preferably not super early in the morning but idrc)

**Comment by sameer-s** [comment]
Okay, looks like we're probably not getting anyone else. I've got stuff going on in the weekend (so I can't do today or tomorrow) but is there an after school day that works best for you? Or maybe we can do next weekend?

**Comment by rewinded** [comment]
Yeah, Tuesday would work for me. Are other people seeing these? seeing as
how no one has responded I imagine others don't have emails notifs on

**Comment by sameer-s** [comment]
Not sure - I don't think I ever explicitly enabled email notifs which means I assume that people are seeing them. We can maybe just tag all the Brussels people?

**Comment by rewinded** [comment]
@01-eric 
@Matth-A 
@KevinPaulsen 
@edelmanjm 
@joshua-bromley 
@derekaloha 
@vikramkashyap 

this is missing Anders Larson and Rudolfo Peralta bc idk their github accounts

**Comment by joshua-bromley** [comment]
I can do Tuesday after school, where would we meet?

**Comment by KevinPaulsen** [comment]
I can do Tuesday. That works for me.

**Comment by sameer-s** [comment]
Not sure where we'll meet yet, I'll ask Steve.

**Comment by vikramkashyap** [comment]
I can do Tuesday, but only after 6. The weekend would be better for me.

**Comment by KevinPaulsen** [comment]
I won’t be able to do Friday or Saturday, but could do almost any other day.

**Comment by rewinded** [comment]
I can pretty much do any day

**Comment by sameer-s** [comment]
Okay, just talked to Steve. He lives nearby so I'll have him run the cars over to my house on Tuesday (I've got some stuff going on today and tomorrow) and we'll make sure that they're at the very least running. If there are any changes that need to be made then we can see about having something on Sunday with this whole group. (Maybe we can just go down to PSU and work in the lobby area).

Right now, are there any changes that will need to be made?

**Comment by rewinded** [comment]
not to my knowledge but even if there were I probably wouldn't be the one to know

**Comment by rewinded** [comment]
do we know the environment we'll be driving it on in Brussels, wall color? carpet color?

**Comment by sameer-s** [comment]
no idea

**Comment by joshua-bromley** [comment]
We know that the carpet is blue. I'm not sure about walls/surroundings

**Comment by sameer-s** [comment]
Steve said we were in the middle - might be no nearby walls. I expect the surroundings to be pretty busy and variable.

**Comment by joshua-bromley** [comment]
The surroundings shouldn't be an issue for steering because image only gives them information below the horizon, speed may have issues

**Comment by KevinPaulsen** [comment]
After the workshop I merged some efficiency improvements to master. I got it to be about 300% faster in my machine.

**Comment by rewinded** [comment]
oh nice, well hopefully that stays true on the car

**Comment by Matth-A** [comment]
Tuesday works for me. Speed will definitely break with surroundings given how finicky it is, but it should be fixable by narrowing down the detection box, adjusting filter constants, and maybe adding some new filter code with object velocity.

**Comment by derekaloha** [comment]
So are we meeting or is that still to be decided?

**Comment by rewinded** [comment]
yeah something like that would be preferable, I've never used telegram but if others want to that's fine with me

**Comment by edelmanjm** [comment]
Text me your phone number so I can add you to Telegram (assuming you've joined it; if not, do that.) In the interest of privacy, I will not be posting mine here.

**Comment by rewinded** [comment]
how am I supposed to text you without your number?

**Comment by edelmanjm** [comment]
@rewinded Some of the people know my number. I'm working on a better solution right now, hold on

**Comment by rewinded** [comment]
alright

**Comment by edelmanjm** [comment]
You've all been added to a private GitHub repository. Post your phone number there and I'll add it to the Telegram group

**Comment by rewinded** [comment]
done

**Comment by edelmanjm** [comment]
Now you can just use the invite link

**Comment by vikramkashyap** [comment]
Can't we just use email instead of making everyone sign up for telegram?
