### ISSUE TITLE
CarControl doesn't work

### ISSUE THREAD

**Issue by Doerd** [AutonomousCarProject/CarControl#3]

**Comment by sameer-s** [comment]
Unable to reproduce issue.

**Comment by Doerd** [comment]
I reproduced it by hitting "run" in Eclipse.

**Comment by sameer-s** [comment]
Interesting. Have you tried turning it off and back on again?

**Comment by Doerd** [comment]
No I didn't think about that

**Comment by sameer-s** [comment]
Resolved in #90 .

**Comment by rewinded** [comment]
good
